/**
 * Generated by scripts/generate-types.mjs — DO NOT EDIT BY HAND.
 *
 * The typed Database contract for the Supabase clients. It is generated from
 * the real schema (supabase/migrations/*.sql applied to an in-memory PGlite
 * instance) and mirrors the shape of `supabase gen types typescript`.
 *
 * Regenerate after any schema change:
 *   npm run db:types:generate
 * CI runs `npm run db:types:check` and fails when this file is stale.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      app_roles: {
        Row: {
        id: string
        key: string
        name: string
        description: string | null
        is_system: boolean
        is_active: boolean
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        key: string
        name: string
        description?: string | null
        is_system?: boolean
        is_active?: boolean
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        key?: string
        name?: string
        description?: string | null
        is_system?: boolean
        is_active?: boolean
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'app_roles_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      client_approvals: {
        Row: {
        id: string
        project_id: string
        delivery_id: string | null
        action: string
        message: string | null
        created_by: string | null
        created_at: string
        }
        Insert: {
        id?: string
        project_id: string
        delivery_id?: string | null
        action: string
        message?: string | null
        created_by?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        delivery_id?: string | null
        action?: string
        message?: string | null
        created_by?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'client_approvals_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_approvals_delivery_id_fkey'
            columns: ['delivery_id']
            isOneToOne: false
            referencedRelation: 'project_deliveries'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_approvals_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      client_messages: {
        Row: {
        id: string
        project_id: string
        author_id: string | null
        body: string
        kind: string
        created_at: string
        }
        Insert: {
        id?: string
        project_id: string
        author_id?: string | null
        body: string
        kind?: string
        created_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        author_id?: string | null
        body?: string
        kind?: string
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'client_messages_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_messages_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      client_shared_files: {
        Row: {
        id: string
        project_id: string
        file_id: string
        shared_by: string | null
        note: string | null
        shared_at: string
        }
        Insert: {
        id?: string
        project_id: string
        file_id: string
        shared_by?: string | null
        note?: string | null
        shared_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        file_id?: string
        shared_by?: string | null
        note?: string | null
        shared_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'client_shared_files_file_id_fkey'
            columns: ['file_id']
            isOneToOne: false
            referencedRelation: 'files'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_shared_files_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_shared_files_shared_by_fkey'
            columns: ['shared_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      clients: {
        Row: {
        id: string
        name: string
        name_en: string | null
        type: string
        industry: string | null
        status: string
        contact_person: string | null
        contact_position: string | null
        email: string | null
        phone: string | null
        location: string | null
        website: string | null
        logo_url: string | null
        notes: string | null
        total_value: number
        project_count: number
        first_project_date: string | null
        last_interaction_date: string | null
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        name: string
        name_en?: string | null
        type?: string
        industry?: string | null
        status?: string
        contact_person?: string | null
        contact_position?: string | null
        email?: string | null
        phone?: string | null
        location?: string | null
        website?: string | null
        logo_url?: string | null
        notes?: string | null
        total_value?: number
        project_count?: number
        first_project_date?: string | null
        last_interaction_date?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        name?: string
        name_en?: string | null
        type?: string
        industry?: string | null
        status?: string
        contact_person?: string | null
        contact_position?: string | null
        email?: string | null
        phone?: string | null
        location?: string | null
        website?: string | null
        logo_url?: string | null
        notes?: string | null
        total_value?: number
        project_count?: number
        first_project_date?: string | null
        last_interaction_date?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
        ]
      }
      comments: {
        Row: {
        id: string
        content: string
        entity_type: string
        entity_id: string
        author_id: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        content: string
        entity_type: string
        entity_id: string
        author_id?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        content?: string
        entity_type?: string
        entity_id?: string
        author_id?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'comments_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      email_delivery_events: {
        Row: {
        id: string
        provider: string
        provider_message_id: string | null
        event_type: string
        recipient_email: string | null
        payload: Json
        received_at: string
        }
        Insert: {
        id?: string
        provider?: string
        provider_message_id?: string | null
        event_type: string
        recipient_email?: string | null
        payload?: Json
        received_at?: string
        }
        Update: {
        id?: string
        provider?: string
        provider_message_id?: string | null
        event_type?: string
        recipient_email?: string | null
        payload?: Json
        received_at?: string
        }
        Relationships: [
        ]
      }
      email_outbox: {
        Row: {
        id: string
        template_key: string
        recipient_email: string
        recipient_user_id: string | null
        payload: Json
        dedupe_key: string
        status: string
        attempts: number
        provider: string | null
        provider_message_id: string | null
        last_error: string | null
        next_attempt_at: string
        sent_at: string | null
        delivered_at: string | null
        created_at: string
        }
        Insert: {
        id?: string
        template_key: string
        recipient_email: string
        recipient_user_id?: string | null
        payload?: Json
        dedupe_key: string
        status?: string
        attempts?: number
        provider?: string | null
        provider_message_id?: string | null
        last_error?: string | null
        next_attempt_at?: string
        sent_at?: string | null
        delivered_at?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        template_key?: string
        recipient_email?: string
        recipient_user_id?: string | null
        payload?: Json
        dedupe_key?: string
        status?: string
        attempts?: number
        provider?: string | null
        provider_message_id?: string | null
        last_error?: string | null
        next_attempt_at?: string
        sent_at?: string | null
        delivered_at?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'email_outbox_recipient_user_id_fkey'
            columns: ['recipient_user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      employee_roles: {
        Row: {
        id: string
        key: string
        name: string
        description: string | null
        is_active: boolean
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        key: string
        name: string
        description?: string | null
        is_active?: boolean
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        key?: string
        name?: string
        description?: string | null
        is_active?: boolean
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'employee_roles_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      files: {
        Row: {
        id: string
        name: string
        type: string
        size: number
        mime_type: string | null
        storage_path: string | null
        project_id: string | null
        client_id: string | null
        uploaded_by: string | null
        starred: boolean
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        name: string
        type?: string
        size?: number
        mime_type?: string | null
        storage_path?: string | null
        project_id?: string | null
        client_id?: string | null
        uploaded_by?: string | null
        starred?: boolean
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        name?: string
        type?: string
        size?: number
        mime_type?: string | null
        storage_path?: string | null
        project_id?: string | null
        client_id?: string | null
        uploaded_by?: string | null
        starred?: boolean
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'files_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'files_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'files_uploaded_by_fkey'
            columns: ['uploaded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      form_questions: {
        Row: {
        id: string
        form_id: string
        question_type: string
        label: string
        help_text: string | null
        placeholder: string | null
        required: boolean
        options: Json
        config: Json
        map_to: string | null
        position: number
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        form_id: string
        question_type: string
        label: string
        help_text?: string | null
        placeholder?: string | null
        required?: boolean
        options?: Json
        config?: Json
        map_to?: string | null
        position?: number
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        form_id?: string
        question_type?: string
        label?: string
        help_text?: string | null
        placeholder?: string | null
        required?: boolean
        options?: Json
        config?: Json
        map_to?: string | null
        position?: number
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_questions_form_id_fkey'
            columns: ['form_id']
            isOneToOne: false
            referencedRelation: 'form_templates'
            referencedColumns: ['id']
          },
        ]
      }
      form_rate_limits: {
        Row: {
        id: string
        session_id: string
        form_id: string
        submitted_at: string
        }
        Insert: {
        id?: string
        session_id?: string
        form_id: string
        submitted_at?: string
        }
        Update: {
        id?: string
        session_id?: string
        form_id?: string
        submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_rate_limits_form_id_fkey'
            columns: ['form_id']
            isOneToOne: false
            referencedRelation: 'form_templates'
            referencedColumns: ['id']
          },
        ]
      }
      form_submission_answers: {
        Row: {
        id: string
        submission_id: string
        question_id: string | null
        question_snapshot: Json
        value: Json | null
        created_at: string
        }
        Insert: {
        id?: string
        submission_id: string
        question_id?: string | null
        question_snapshot: Json
        value?: Json | null
        created_at?: string
        }
        Update: {
        id?: string
        submission_id?: string
        question_id?: string | null
        question_snapshot?: Json
        value?: Json | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submission_answers_question_id_fkey'
            columns: ['question_id']
            isOneToOne: false
            referencedRelation: 'form_questions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submission_answers_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      form_submission_attachments: {
        Row: {
        id: string
        submission_id: string
        question_id: string | null
        name: string
        size: number
        mime_type: string | null
        storage_path: string
        uploaded_by: string | null
        created_at: string
        }
        Insert: {
        id?: string
        submission_id: string
        question_id?: string | null
        name: string
        size?: number
        mime_type?: string | null
        storage_path: string
        uploaded_by?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        submission_id?: string
        question_id?: string | null
        name?: string
        size?: number
        mime_type?: string | null
        storage_path?: string
        uploaded_by?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submission_attachments_question_id_fkey'
            columns: ['question_id']
            isOneToOne: false
            referencedRelation: 'form_questions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submission_attachments_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      form_submission_events: {
        Row: {
        id: string
        submission_id: string
        actor_id: string | null
        event_type: string
        old_value: string | null
        new_value: string | null
        note: string | null
        metadata: Json
        created_at: string
        }
        Insert: {
        id?: string
        submission_id: string
        actor_id?: string | null
        event_type: string
        old_value?: string | null
        new_value?: string | null
        note?: string | null
        metadata?: Json
        created_at?: string
        }
        Update: {
        id?: string
        submission_id?: string
        actor_id?: string | null
        event_type?: string
        old_value?: string | null
        new_value?: string | null
        note?: string | null
        metadata?: Json
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submission_events_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submission_events_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      form_submission_fingerprints: {
        Row: {
        id: string
        form_id: string
        fingerprint: string
        submitted_at: string
        }
        Insert: {
        id?: string
        form_id: string
        fingerprint: string
        submitted_at?: string
        }
        Update: {
        id?: string
        form_id?: string
        fingerprint?: string
        submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submission_fingerprints_form_id_fkey'
            columns: ['form_id']
            isOneToOne: false
            referencedRelation: 'form_templates'
            referencedColumns: ['id']
          },
        ]
      }
      form_submission_notes: {
        Row: {
        id: string
        submission_id: string
        author_id: string
        note: string
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        submission_id: string
        author_id: string
        note: string
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        submission_id?: string
        author_id?: string
        note?: string
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submission_notes_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submission_notes_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      form_submissions: {
        Row: {
        id: string
        form_id: string
        form_version: number
        status: string
        respondent_name: string | null
        respondent_email: string | null
        respondent_phone: string | null
        company_name: string | null
        client_id: string | null
        project_id: string | null
        created_by: string | null
        submitted_at: string
        created_at: string
        updated_at: string
        reviewer_id: string | null
        reviewed_at: string | null
        converted_at: string | null
        converted_by: string | null
        reference_number: string
        tracking_token: string
        }
        Insert: {
        id?: string
        form_id: string
        form_version?: number
        status?: string
        respondent_name?: string | null
        respondent_email?: string | null
        respondent_phone?: string | null
        company_name?: string | null
        client_id?: string | null
        project_id?: string | null
        created_by?: string | null
        submitted_at?: string
        created_at?: string
        updated_at?: string
        reviewer_id?: string | null
        reviewed_at?: string | null
        converted_at?: string | null
        converted_by?: string | null
        reference_number?: string
        tracking_token?: string
        }
        Update: {
        id?: string
        form_id?: string
        form_version?: number
        status?: string
        respondent_name?: string | null
        respondent_email?: string | null
        respondent_phone?: string | null
        company_name?: string | null
        client_id?: string | null
        project_id?: string | null
        created_by?: string | null
        submitted_at?: string
        created_at?: string
        updated_at?: string
        reviewer_id?: string | null
        reviewed_at?: string | null
        converted_at?: string | null
        converted_by?: string | null
        reference_number?: string
        tracking_token?: string
        }
        Relationships: [
          {
            foreignKeyName: 'form_submissions_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submissions_converted_by_fkey'
            columns: ['converted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submissions_form_id_fkey'
            columns: ['form_id']
            isOneToOne: false
            referencedRelation: 'form_templates'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submissions_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'form_submissions_reviewer_id_fkey'
            columns: ['reviewer_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      form_templates: {
        Row: {
        id: string
        slug: string
        title: string
        description: string | null
        status: string
        version: number
        settings: Json
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        slug: string
        title: string
        description?: string | null
        status?: string
        version?: number
        settings?: Json
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        slug?: string
        title?: string
        description?: string | null
        status?: string
        version?: number
        settings?: Json
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
        ]
      }
      intake_attachments: {
        Row: {
        id: string
        intake_id: string
        name: string
        size: number
        mime_type: string | null
        storage_path: string
        uploaded_by: string | null
        created_at: string
        }
        Insert: {
        id?: string
        intake_id: string
        name: string
        size?: number
        mime_type?: string | null
        storage_path: string
        uploaded_by?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        intake_id?: string
        name?: string
        size?: number
        mime_type?: string | null
        storage_path?: string
        uploaded_by?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'intake_attachments_intake_id_fkey'
            columns: ['intake_id']
            isOneToOne: false
            referencedRelation: 'intake_forms'
            referencedColumns: ['id']
          },
        ]
      }
      intake_forms: {
        Row: {
        id: string
        service_type: string | null
        status: string
        contact_name: string | null
        contact_email: string | null
        company_name: string | null
        phone: string | null
        data: Json
        client_id: string | null
        project_id: string | null
        created_by: string | null
        submitted_at: string | null
        created_at: string
        updated_at: string
        service_types: string[]
        }
        Insert: {
        id?: string
        service_type?: string | null
        status?: string
        contact_name?: string | null
        contact_email?: string | null
        company_name?: string | null
        phone?: string | null
        data?: Json
        client_id?: string | null
        project_id?: string | null
        created_by?: string | null
        submitted_at?: string | null
        created_at?: string
        updated_at?: string
        service_types?: string[]
        }
        Update: {
        id?: string
        service_type?: string | null
        status?: string
        contact_name?: string | null
        contact_email?: string | null
        company_name?: string | null
        phone?: string | null
        data?: Json
        client_id?: string | null
        project_id?: string | null
        created_by?: string | null
        submitted_at?: string | null
        created_at?: string
        updated_at?: string
        service_types?: string[]
        }
        Relationships: [
          {
            foreignKeyName: 'intake_forms_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'intake_forms_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      intake_projects: {
        Row: {
        id: string
        intake_id: string
        project_id: string
        service_type: string
        created_at: string
        }
        Insert: {
        id?: string
        intake_id: string
        project_id: string
        service_type: string
        created_at?: string
        }
        Update: {
        id?: string
        intake_id?: string
        project_id?: string
        service_type?: string
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'intake_projects_intake_id_fkey'
            columns: ['intake_id']
            isOneToOne: false
            referencedRelation: 'intake_forms'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'intake_projects_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      interactions: {
        Row: {
        id: string
        type: string
        title: string
        description: string | null
        client_id: string
        project_id: string | null
        date: string
        created_by: string | null
        created_at: string
        }
        Insert: {
        id?: string
        type?: string
        title: string
        description?: string | null
        client_id: string
        project_id?: string | null
        date?: string
        created_by?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        type?: string
        title?: string
        description?: string | null
        client_id?: string
        project_id?: string | null
        date?: string
        created_by?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'interactions_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'interactions_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'interactions_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      notifications: {
        Row: {
        id: string
        recipient_id: string
        actor_id: string | null
        project_id: string | null
        type: string
        title: string
        message: string
        action_url: string | null
        read_at: string | null
        created_at: string
        metadata: Json
        submission_id: string | null
        task_id: string | null
        event: string | null
        dedupe_key: string | null
        }
        Insert: {
        id?: string
        recipient_id: string
        actor_id?: string | null
        project_id?: string | null
        type?: string
        title: string
        message: string
        action_url?: string | null
        read_at?: string | null
        created_at?: string
        metadata?: Json
        submission_id?: string | null
        task_id?: string | null
        event?: string | null
        dedupe_key?: string | null
        }
        Update: {
        id?: string
        recipient_id?: string
        actor_id?: string | null
        project_id?: string | null
        type?: string
        title?: string
        message?: string
        action_url?: string | null
        read_at?: string | null
        created_at?: string
        metadata?: Json
        submission_id?: string | null
        task_id?: string | null
        event?: string | null
        dedupe_key?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_recipient_id_fkey'
            columns: ['recipient_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_task_id_fkey'
            columns: ['task_id']
            isOneToOne: false
            referencedRelation: 'tasks'
            referencedColumns: ['id']
          },
        ]
      }
      permissions: {
        Row: {
        id: string
        key: string
        name: string
        category: string
        description: string | null
        created_at: string
        }
        Insert: {
        id?: string
        key: string
        name: string
        category?: string
        description?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        key?: string
        name?: string
        category?: string
        description?: string | null
        created_at?: string
        }
        Relationships: [
        ]
      }
      portfolio_categories: {
        Row: {
        id: string
        name: string
        slug: string
        is_active: boolean
        display_order: number
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        name: string
        slug: string
        is_active?: boolean
        display_order?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        name?: string
        slug?: string
        is_active?: boolean
        display_order?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'portfolio_categories_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      portfolio_project_images: {
        Row: {
        id: string
        project_id: string
        storage_path: string
        alt_text: string | null
        display_order: number
        uploaded_by: string | null
        created_at: string
        }
        Insert: {
        id?: string
        project_id: string
        storage_path: string
        alt_text?: string | null
        display_order?: number
        uploaded_by?: string | null
        created_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        storage_path?: string
        alt_text?: string | null
        display_order?: number
        uploaded_by?: string | null
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'portfolio_project_images_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'portfolio_projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'portfolio_project_images_uploaded_by_fkey'
            columns: ['uploaded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      portfolio_projects: {
        Row: {
        id: string
        title: string
        slug: string
        cover_image_path: string | null
        description: string | null
        client_name: string | null
        category_id: string | null
        services: string[]
        project_date: string | null
        external_url: string | null
        featured: boolean
        published: boolean
        archived: boolean
        display_order: number
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        title: string
        slug: string
        cover_image_path?: string | null
        description?: string | null
        client_name?: string | null
        category_id?: string | null
        services?: string[]
        project_date?: string | null
        external_url?: string | null
        featured?: boolean
        published?: boolean
        archived?: boolean
        display_order?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        title?: string
        slug?: string
        cover_image_path?: string | null
        description?: string | null
        client_name?: string | null
        category_id?: string | null
        services?: string[]
        project_date?: string | null
        external_url?: string | null
        featured?: boolean
        published?: boolean
        archived?: boolean
        display_order?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'portfolio_projects_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'portfolio_categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'portfolio_projects_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
        id: string
        email: string
        full_name: string | null
        avatar_url: string | null
        role: Database['public']['Enums']['app_role']
        agency_name: string | null
        agency_website: string | null
        phone: string | null
        bio: string | null
        created_at: string
        updated_at: string
        status: string
        employee_role_id: string | null
        client_id: string | null
        role_id: string | null
        job_title: string | null
        department: string | null
        specialization: string | null
        location: string | null
        portfolio_url: string | null
        whatsapp: string | null
        social_links: Json
        must_change_password: boolean
        skills: string | null
        experience: string | null
        certifications: string | null
        previous_projects: string | null
        linkedin: string | null
        behance: string | null
        instagram: string | null
        facebook: string | null
        twitter: string | null
        personal_website: string | null
        other_social_links: Json
        }
        Insert: {
        id: string
        email: string
        full_name?: string | null
        avatar_url?: string | null
        role?: Database['public']['Enums']['app_role']
        agency_name?: string | null
        agency_website?: string | null
        phone?: string | null
        bio?: string | null
        created_at?: string
        updated_at?: string
        status?: string
        employee_role_id?: string | null
        client_id?: string | null
        role_id?: string | null
        job_title?: string | null
        department?: string | null
        specialization?: string | null
        location?: string | null
        portfolio_url?: string | null
        whatsapp?: string | null
        social_links?: Json
        must_change_password?: boolean
        skills?: string | null
        experience?: string | null
        certifications?: string | null
        previous_projects?: string | null
        linkedin?: string | null
        behance?: string | null
        instagram?: string | null
        facebook?: string | null
        twitter?: string | null
        personal_website?: string | null
        other_social_links?: Json
        }
        Update: {
        id?: string
        email?: string
        full_name?: string | null
        avatar_url?: string | null
        role?: Database['public']['Enums']['app_role']
        agency_name?: string | null
        agency_website?: string | null
        phone?: string | null
        bio?: string | null
        created_at?: string
        updated_at?: string
        status?: string
        employee_role_id?: string | null
        client_id?: string | null
        role_id?: string | null
        job_title?: string | null
        department?: string | null
        specialization?: string | null
        location?: string | null
        portfolio_url?: string | null
        whatsapp?: string | null
        social_links?: Json
        must_change_password?: boolean
        skills?: string | null
        experience?: string | null
        certifications?: string | null
        previous_projects?: string | null
        linkedin?: string | null
        behance?: string | null
        instagram?: string | null
        facebook?: string | null
        twitter?: string | null
        personal_website?: string | null
        other_social_links?: Json
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'profiles_employee_role_id_fkey'
            columns: ['employee_role_id']
            isOneToOne: false
            referencedRelation: 'employee_roles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'profiles_role_id_fkey'
            columns: ['role_id']
            isOneToOne: false
            referencedRelation: 'app_roles'
            referencedColumns: ['id']
          },
        ]
      }
      project_activity: {
        Row: {
        id: string
        project_id: string
        actor_id: string | null
        event_type: string
        old_value: string | null
        new_value: string | null
        metadata: Json
        created_at: string
        }
        Insert: {
        id?: string
        project_id: string
        actor_id?: string | null
        event_type: string
        old_value?: string | null
        new_value?: string | null
        metadata?: Json
        created_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        actor_id?: string | null
        event_type?: string
        old_value?: string | null
        new_value?: string | null
        metadata?: Json
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_activity_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_activity_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      project_deliveries: {
        Row: {
        id: string
        project_id: string
        version: number
        status: string
        notes: string | null
        delivered_at: string | null
        delivered_by: string | null
        approval_state: string
        approval_recorded_by: string | null
        approval_recorded_at: string | null
        approval_note: string | null
        revision_note: string | null
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        project_id: string
        version: number
        status?: string
        notes?: string | null
        delivered_at?: string | null
        delivered_by?: string | null
        approval_state?: string
        approval_recorded_by?: string | null
        approval_recorded_at?: string | null
        approval_note?: string | null
        revision_note?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        project_id?: string
        version?: number
        status?: string
        notes?: string | null
        delivered_at?: string | null
        delivered_by?: string | null
        approval_state?: string
        approval_recorded_by?: string | null
        approval_recorded_at?: string | null
        approval_note?: string | null
        revision_note?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_deliveries_approval_recorded_by_fkey'
            columns: ['approval_recorded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_deliveries_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_deliveries_delivered_by_fkey'
            columns: ['delivered_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_deliveries_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      project_delivery_files: {
        Row: {
        delivery_id: string
        file_id: string
        added_by: string | null
        added_at: string
        }
        Insert: {
        delivery_id: string
        file_id: string
        added_by?: string | null
        added_at?: string
        }
        Update: {
        delivery_id?: string
        file_id?: string
        added_by?: string | null
        added_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_delivery_files_added_by_fkey'
            columns: ['added_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_delivery_files_delivery_id_fkey'
            columns: ['delivery_id']
            isOneToOne: false
            referencedRelation: 'project_deliveries'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_delivery_files_file_id_fkey'
            columns: ['file_id']
            isOneToOne: false
            referencedRelation: 'files'
            referencedColumns: ['id']
          },
        ]
      }
      project_members: {
        Row: {
        project_id: string
        user_id: string
        assigned_by: string | null
        assigned_at: string
        }
        Insert: {
        project_id: string
        user_id: string
        assigned_by?: string | null
        assigned_at?: string
        }
        Update: {
        project_id?: string
        user_id?: string
        assigned_by?: string | null
        assigned_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_members_assigned_by_fkey'
            columns: ['assigned_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_members_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      projects: {
        Row: {
        id: string
        name: string
        description: string | null
        client_id: string
        type: string
        status: string
        phase: number
        phase_name: string | null
        progress: number
        budget: number | null
        currency: string
        start_date: string | null
        due_date: string | null
        completed_date: string | null
        created_by: string | null
        created_at: string
        updated_at: string
        priority: string
        owner_id: string | null
        manager_id: string | null
        source_submission_id: string | null
        health: string
        archived_at: string | null
        archived_by: string | null
        }
        Insert: {
        id?: string
        name: string
        description?: string | null
        client_id: string
        type?: string
        status?: string
        phase?: number
        phase_name?: string | null
        progress?: number
        budget?: number | null
        currency?: string
        start_date?: string | null
        due_date?: string | null
        completed_date?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        priority?: string
        owner_id?: string | null
        manager_id?: string | null
        source_submission_id?: string | null
        health?: string
        archived_at?: string | null
        archived_by?: string | null
        }
        Update: {
        id?: string
        name?: string
        description?: string | null
        client_id?: string
        type?: string
        status?: string
        phase?: number
        phase_name?: string | null
        progress?: number
        budget?: number | null
        currency?: string
        start_date?: string | null
        due_date?: string | null
        completed_date?: string | null
        created_by?: string | null
        created_at?: string
        updated_at?: string
        priority?: string
        owner_id?: string | null
        manager_id?: string | null
        source_submission_id?: string | null
        health?: string
        archived_at?: string | null
        archived_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'projects_archived_by_fkey'
            columns: ['archived_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'projects_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'projects_manager_id_fkey'
            columns: ['manager_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'projects_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'projects_source_submission_id_fkey'
            columns: ['source_submission_id']
            isOneToOne: false
            referencedRelation: 'form_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      reminder_events: {
        Row: {
        id: string
        kind: string
        entity_type: string
        entity_id: string
        recipient_id: string | null
        notification_id: string | null
        due_date: string
        dedupe_key: string
        role: string
        created_at: string
        }
        Insert: {
        id?: string
        kind: string
        entity_type: string
        entity_id: string
        recipient_id?: string | null
        notification_id?: string | null
        due_date: string
        dedupe_key: string
        role?: string
        created_at?: string
        }
        Update: {
        id?: string
        kind?: string
        entity_type?: string
        entity_id?: string
        recipient_id?: string | null
        notification_id?: string | null
        due_date?: string
        dedupe_key?: string
        role?: string
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'reminder_events_notification_id_fkey'
            columns: ['notification_id']
            isOneToOne: false
            referencedRelation: 'notifications'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'reminder_events_recipient_id_fkey'
            columns: ['recipient_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      role_permissions: {
        Row: {
        role_id: string
        permission_id: string
        created_at: string
        }
        Insert: {
        role_id: string
        permission_id: string
        created_at?: string
        }
        Update: {
        role_id?: string
        permission_id?: string
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'role_permissions_permission_id_fkey'
            columns: ['permission_id']
            isOneToOne: false
            referencedRelation: 'permissions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'role_permissions_role_id_fkey'
            columns: ['role_id']
            isOneToOne: false
            referencedRelation: 'app_roles'
            referencedColumns: ['id']
          },
        ]
      }
      task_activity: {
        Row: {
        id: string
        task_id: string
        project_id: string
        actor_id: string | null
        event_type: string
        old_value: string | null
        new_value: string | null
        metadata: Json
        created_at: string
        }
        Insert: {
        id?: string
        task_id: string
        project_id: string
        actor_id?: string | null
        event_type: string
        old_value?: string | null
        new_value?: string | null
        metadata?: Json
        created_at?: string
        }
        Update: {
        id?: string
        task_id?: string
        project_id?: string
        actor_id?: string | null
        event_type?: string
        old_value?: string | null
        new_value?: string | null
        metadata?: Json
        created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'task_activity_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'task_activity_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'task_activity_task_id_fkey'
            columns: ['task_id']
            isOneToOne: false
            referencedRelation: 'tasks'
            referencedColumns: ['id']
          },
        ]
      }
      tasks: {
        Row: {
        id: string
        title: string
        description: string | null
        project_id: string
        status: string
        priority: string
        assignee_id: string | null
        due_date: string | null
        completed_date: string | null
        tags: string[]
        comments_count: number
        attachments_count: number
        created_by: string | null
        created_at: string
        updated_at: string
        }
        Insert: {
        id?: string
        title: string
        description?: string | null
        project_id: string
        status?: string
        priority?: string
        assignee_id?: string | null
        due_date?: string | null
        completed_date?: string | null
        tags?: string[]
        comments_count?: number
        attachments_count?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Update: {
        id?: string
        title?: string
        description?: string | null
        project_id?: string
        status?: string
        priority?: string
        assignee_id?: string | null
        due_date?: string | null
        completed_date?: string | null
        tags?: string[]
        comments_count?: number
        attachments_count?: number
        created_by?: string | null
        created_at?: string
        updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tasks_assignee_id_fkey'
            columns: ['assignee_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'tasks_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'tasks_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      add_client_portal_feedback: {
        Args: {
          p_project_id: string | null
          p_body: string | null
        }
        Returns: Database['public']['Tables']['client_messages']['Row']
      }
      add_client_visible_message: {
        Args: {
          p_project_id: string | null
          p_body: string | null
        }
        Returns: Database['public']['Tables']['client_messages']['Row']
      }
      add_form_submission_note: {
        Args: {
          p_submission_id: string | null
          p_note: string | null
        }
        Returns: Database['public']['Tables']['form_submission_notes']['Row']
      }
      add_permission: {
        Args: {
          p_key: string | null
          p_name: string | null
          p_category: string | null
          p_description: string | null
        }
        Returns: Database['public']['Tables']['permissions']['Row']
      }
      add_project_delivery_file: {
        Args: {
          p_project_id: string | null
          p_file_id: string | null
        }
        Returns: Database['public']['Tables']['project_deliveries']['Row']
      }
      add_task_note: {
        Args: {
          p_task_id: string | null
          p_note: string | null
        }
        Returns: Database['public']['Tables']['task_activity']['Row']
      }
      admin_create_client_account: {
        Args: {
          p_client_id: string | null
          p_email: string | null
          p_full_name?: string | null
          p_status?: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      admin_create_team_member: {
        Args: {
          p_email: string | null
          p_full_name: string | null
          p_phone?: string | null
          p_whatsapp?: string | null
          p_avatar_url?: string | null
          p_job_title?: string | null
          p_department?: string | null
          p_specialization?: string | null
          p_bio?: string | null
          p_location?: string | null
          p_portfolio_url?: string | null
          p_social_links?: Json | null
          p_role_id?: string | null
          p_employee_role_id?: string | null
          p_status?: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      admin_delete_client_account: {
        Args: {
          p_user_id: string | null
        }
        Returns: boolean
      }
      admin_delete_team_member: {
        Args: {
          p_user_id: string | null
        }
        Returns: boolean
      }
      admin_update_client_account: {
        Args: {
          p_user_id: string | null
          p_email?: string | null
          p_full_name?: string | null
          p_client_id?: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      admin_update_team_member: {
        Args: {
          p_user_id: string | null
          p_email?: string | null
          p_full_name?: string | null
          p_phone?: string | null
          p_whatsapp?: string | null
          p_avatar_url?: string | null
          p_job_title?: string | null
          p_department?: string | null
          p_specialization?: string | null
          p_bio?: string | null
          p_location?: string | null
          p_portfolio_url?: string | null
          p_social_links?: Json | null
          p_role_id?: string | null
          p_employee_role_id?: string | null
          p_status?: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      approve_client_portal_delivery: {
        Args: {
          p_project_id: string | null
          p_note?: string | null
        }
        Returns: Database['public']['Tables']['client_approvals']['Row']
      }
      archive_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      assert_client_portal_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      assert_staff_can_access_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      assign_form_submission_reviewer: {
        Args: {
          p_submission_id: string | null
          p_reviewer_id: string | null
          p_note?: string | null
        }
        Returns: boolean
      }
      assign_user_role: {
        Args: {
          p_user_id: string | null
          p_role_id: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      bump_form_template_version: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      can_access_client: {
        Args: {
          target_client_id: string | null
        }
        Returns: boolean
      }
      can_access_entity: {
        Args: {
          target_type: string | null
          target_id: string | null
        }
        Returns: boolean
      }
      can_access_project: {
        Args: {
          target_project_id: string | null
        }
        Returns: boolean
      }
      can_user_access_project: {
        Args: {
          p_user_id: string | null
          p_project_id: string | null
        }
        Returns: boolean
      }
      cleanup_form_rate_limits: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      cleanup_form_submission_fingerprints: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      client_can_read_file: {
        Args: {
          p_file_id: string | null
        }
        Returns: boolean
      }
      client_can_read_storage_object: {
        Args: {
          p_object_name: string | null
        }
        Returns: boolean
      }
      client_owns_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: boolean
      }
      client_portal_client_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      complete_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      convert_submission_to_project: {
        Args: {
          p_submission_id: string | null
          p_client_id: string | null
          p_new_client: Json | null
          p_project_name: string | null
          p_description: string | null
          p_project_type: string | null
          p_priority: string | null
          p_status: string | null
          p_phase: number | null
          p_phase_name: string | null
          p_start_date: string | null
          p_due_date: string | null
          p_budget: number | null
          p_currency: string | null
          p_owner_id: string | null
          p_manager_id: string | null
          p_team_member_ids: string[] | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      create_app_role: {
        Args: {
          p_name: string | null
          p_description: string | null
        }
        Returns: Database['public']['Tables']['app_roles']['Row']
      }
      current_project_delivery: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['project_deliveries']['Row']
      }
      current_user_client_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      current_user_role: {
        Args: Record<PropertyKey, never>
        Returns: Database['public']['Enums']['app_role']
      }
      delete_app_role: {
        Args: {
          p_role_id: string | null
        }
        Returns: boolean
      }
      delete_form_submission_note: {
        Args: {
          p_note_id: string | null
        }
        Returns: boolean
      }
      duplicate_form_template: {
        Args: {
          p_form_id: string | null
        }
        Returns: Database['public']['Tables']['form_templates']['Row']
      }
      email_client_recipient_ok: {
        Args: {
          p_user_id: string | null
        }
        Returns: boolean
      }
      email_staff_recipient_ok: {
        Args: {
          p_user_id: string | null
        }
        Returns: boolean
      }
      emit_in_app_notification: {
        Args: {
          p_recipient_id: string | null
          p_event: string | null
          p_type: string | null
          p_title: string | null
          p_message: string | null
          p_action_url: string | null
          p_dedupe_key: string | null
          p_actor_id?: string | null
          p_project_id?: string | null
          p_submission_id?: string | null
          p_task_id?: string | null
          p_metadata?: Json | null
        }
        Returns: string
      }
      enforce_admin_auto_project_configuration: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enforce_delivery_file_same_project: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enforce_delivery_file_unlocked: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enforce_project_status_transition: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enforce_task_assignee_guard: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_client_collaboration_emails: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_delivery_client_email: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_email: {
        Args: {
          p_template_key: string | null
          p_recipient_email: string | null
          p_recipient_user_id?: string | null
          p_payload?: Json | null
          p_dedupe_key?: string | null
        }
        Returns: string
      }
      enqueue_project_lead_email: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_submission_emails: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_task_assigned_email: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      enqueue_team_member_email: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      finalize_automated_submission_conversion: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      generate_submission_reference: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      get_client_portal_client: {
        Args: Record<PropertyKey, never>
        Returns: Record<string, unknown>[]
      }
      get_client_portal_collaboration: {
        Args: {
          p_project_id: string | null
        }
        Returns: Json
      }
      get_client_portal_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Record<string, unknown>[]
      }
      get_client_portal_projects: {
        Args: Record<PropertyKey, never>
        Returns: Record<string, unknown>[]
      }
      get_operational_analytics: {
        Args: {
          p_days?: number | null
        }
        Returns: Json
      }
      get_public_portfolio_project: {
        Args: {
          p_slug: string | null
        }
        Returns: Record<string, unknown>[]
      }
      get_public_portfolio_projects: {
        Args: Record<PropertyKey, never>
        Returns: Record<string, unknown>[]
      }
      get_public_submission_tracking: {
        Args: {
          p_tracking_key: string | null
        }
        Returns: Json
      }
      get_storage_audit_summary: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      get_submission_inbox_page: {
        Args: {
          p_search?: string | null
          p_status?: string | null
          p_reviewer_mode?: string | null
          p_reviewer_id?: string | null
          p_form_id?: string | null
          p_sort?: string | null
          p_page?: number | null
          p_page_size?: number | null
        }
        Returns: Record<string, unknown>
      }
      get_submission_pipeline_counts: {
        Args: Record<PropertyKey, never>
        Returns: Record<string, unknown>
      }
      get_user_permissions: {
        Args: Record<PropertyKey, never>
        Returns: string[]
      }
      guard_form_template_delete: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      guard_internal_account_creation: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      guard_locked_delivery_file_delete: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      guard_profile_email_matches_auth: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      handle_new_user: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      has_any_permission: {
        Args: {
          required_permissions: string[] | null
        }
        Returns: boolean
      }
      has_permission: {
        Args: {
          required_permission: string | null
        }
        Returns: boolean
      }
      is_active: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      is_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      is_form_question_visible: {
        Args: {
          p_q: Database['public']['Tables']['form_questions']['Row'] | null
          p_answers: Json | null
        }
        Returns: boolean
      }
      is_manager_or_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      is_public_portfolio_image: {
        Args: {
          object_name: string | null
        }
        Returns: boolean
      }
      is_staff: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      link_automated_project_to_submission: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      list_permissions: {
        Args: Record<PropertyKey, never>
        Returns: Database['public']['Tables']['permissions']['Row'][]
      }
      list_roles: {
        Args: Record<PropertyKey, never>
        Returns: Record<string, unknown>[]
      }
      list_task_assignees: {
        Args: {
          p_project_id: string | null
        }
        Returns: Record<string, unknown>[]
      }
      mark_delivery_ready: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      mark_password_changed: {
        Args: {
          p_user_id: string | null
        }
        Returns: undefined
      }
      mark_project_delivered: {
        Args: {
          p_project_id: string | null
          p_note?: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      must_change_password_pending: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      notification_display_name: {
        Args: {
          p_user_id: string | null
        }
        Returns: string
      }
      notify_client_accounts: {
        Args: {
          p_client_id: string | null
          p_event: string | null
          p_type: string | null
          p_title: string | null
          p_message: string | null
          p_action_url: string | null
          p_dedupe_prefix: string | null
          p_actor_id?: string | null
          p_project_id?: string | null
          p_metadata?: Json | null
        }
        Returns: number
      }
      notify_delivery_ready: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_form_submission: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_project_assignment: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_project_created: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_project_owners: {
        Args: {
          p_project_id: string | null
          p_type: string | null
          p_title: string | null
          p_message: string | null
          p_action_url: string | null
          p_metadata?: Json | null
        }
        Returns: undefined
      }
      notify_project_update: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_staff_with_permission: {
        Args: {
          p_permission: string | null
          p_event: string | null
          p_type: string | null
          p_title: string | null
          p_message: string | null
          p_action_url: string | null
          p_dedupe_prefix: string | null
          p_actor_id?: string | null
          p_project_id?: string | null
          p_submission_id?: string | null
          p_task_id?: string | null
          p_metadata?: Json | null
        }
        Returns: number
      }
      notify_submission_review_events: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_task_assignment: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      notify_task_updated: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      prepare_project_delivery: {
        Args: {
          p_project_id: string | null
          p_notes?: string | null
        }
        Returns: Database['public']['Tables']['project_deliveries']['Row']
      }
      project_can_complete: {
        Args: {
          p_project_id: string | null
        }
        Returns: boolean
      }
      project_completion_blockers: {
        Args: {
          p_project_id: string | null
        }
        Returns: string[]
      }
      project_delivery_file_count: {
        Args: {
          p_project_id: string | null
        }
        Returns: number
      }
      project_delivery_readiness: {
        Args: {
          p_project_id: string | null
        }
        Returns: Json
      }
      protect_project_submission_reference: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      record_deadline_reminder: {
        Args: {
          p_kind: string | null
          p_entity_type: string | null
          p_entity_id: string | null
          p_recipient_id: string | null
          p_due_date: string | null
          p_role: string | null
          p_event: string | null
          p_title: string | null
          p_message: string | null
          p_action_url: string | null
          p_project_id: string | null
          p_task_id: string | null
          p_metadata?: Json | null
        }
        Returns: boolean
      }
      record_internal_client_approval: {
        Args: {
          p_project_id: string | null
          p_note: string | null
          p_state?: string | null
        }
        Returns: Database['public']['Tables']['project_deliveries']['Row']
      }
      record_project_activity: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      record_project_file_activity: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      record_project_member_activity: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      record_task_activity: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      remove_project_delivery_file: {
        Args: {
          p_project_id: string | null
          p_file_id: string | null
        }
        Returns: boolean
      }
      reorder_form_questions: {
        Args: {
          p_form_id: string | null
          p_question_ids: string[] | null
        }
        Returns: number
      }
      request_client_portal_revision: {
        Args: {
          p_project_id: string | null
          p_note: string | null
        }
        Returns: Database['public']['Tables']['client_approvals']['Row']
      }
      request_project_revision: {
        Args: {
          p_project_id: string | null
          p_note: string | null
        }
        Returns: Database['public']['Tables']['project_deliveries']['Row']
      }
      run_deadline_reminders: {
        Args: {
          p_today?: string | null
        }
        Returns: Json
      }
      set_role_permissions: {
        Args: {
          p_role_id: string | null
          p_permission_keys: string[] | null
        }
        Returns: Database['public']['Tables']['app_roles']['Row']
      }
      set_updated_at: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      set_user_client_link: {
        Args: {
          target_user_id: string | null
          new_client_id: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      set_user_employee_role: {
        Args: {
          target_user_id: string | null
          new_employee_role_id: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      set_user_role: {
        Args: {
          target_user_id: string | null
          new_role: Database['public']['Enums']['app_role'] | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      set_user_status: {
        Args: {
          target_user_id: string | null
          new_status: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      share_delivered_files_with_client: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      share_project_file_with_client: {
        Args: {
          p_project_id: string | null
          p_file_id: string | null
          p_note?: string | null
        }
        Returns: Database['public']['Tables']['client_shared_files']['Row']
      }
      submit_dynamic_form: {
        Args: {
          p_form_id: string | null
          p_answers: Json | null
        }
        Returns: Database['public']['Tables']['form_submissions']['Row']
      }
      sync_delivery_on_project_status: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      sync_profile_role: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      sync_project_lead_membership: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      unarchive_project: {
        Args: {
          p_project_id: string | null
        }
        Returns: Database['public']['Tables']['projects']['Row']
      }
      unassign_tasks_on_member_removal: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      unshare_project_file_with_client: {
        Args: {
          p_project_id: string | null
          p_file_id: string | null
        }
        Returns: boolean
      }
      update_app_role: {
        Args: {
          p_role_id: string | null
          p_name: string | null
          p_description: string | null
          p_is_active: boolean | null
        }
        Returns: Database['public']['Tables']['app_roles']['Row']
      }
      update_form_submission_status: {
        Args: {
          p_submission_id: string | null
          p_status: string | null
          p_note?: string | null
        }
        Returns: boolean
      }
      update_own_enhanced_profile: {
        Args: {
          p_user_id: string | null
          p_full_name: string | null
          p_phone: string | null
          p_whatsapp: string | null
          p_bio: string | null
          p_job_title: string | null
          p_skills: string | null
          p_experience: string | null
          p_previous_projects: string | null
          p_certifications: string | null
          p_location: string | null
          p_portfolio_url: string | null
          p_linkedin: string | null
          p_behance: string | null
          p_instagram: string | null
          p_facebook: string | null
          p_twitter: string | null
          p_personal_website: string | null
          p_other_social_links: Json | null
          p_avatar_url: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      update_own_profile: {
        Args: {
          new_full_name: string | null
          new_avatar_url: string | null
          new_agency_name: string | null
          new_agency_website: string | null
          new_phone: string | null
          new_bio: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      user_has_permission: {
        Args: {
          p_user_id: string | null
          p_permission: string | null
        }
        Returns: boolean
      }
      user_role_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      valid_project_status_transition: {
        Args: {
          p_from: string | null
          p_to: string | null
        }
        Returns: boolean
      }
    }
    Enums: {
      app_role: 'admin' | 'manager' | 'employee' | 'client'
    }
    CompositeTypes: { [_ in never]: never }
  }
}

